DROP TABLE BOOK_LIST;
DROP TABLE BOOK_ORDER;
DROP SEQUENCE BOOK_SEQ;
DROP SEQUENCE ORDER_SEQ;
TRUNCATE TABLE BOOK_ORDER; --TRUNCATE롤백안됨, 자료지우기, 대신 빠름

CREATE TABLE BOOK_LIST(
    BOOK_NO NUMBER(30) PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    WRITER VARCHAR2(100) NOT NULL,
    PRICE NUMBER(30) NOT NULL,
    STOCK NUMBER(30) NOT NULL
);

CREATE SEQUENCE BOOK_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;
       
CREATE TABLE BOOK_ORDER(
    ORDER_NO NUMBER(30) PRIMARY KEY,
    BOOK_NO NUMBER(30) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    WRITER VARCHAR2(100) NOT NULL,
    PRICE NUMBER(30) NOT NULL,
    COUNT NUMBER(30)
);

CREATE SEQUENCE ORDER_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;

commit;

INSERT INTO BOOK_LIST VALUES(BOOK_SEQ.NEXTVAL, '혼자 공부하는 자바', '신용권', 24000, 10);
INSERT INTO BOOK_LIST VALUES(BOOK_SEQ.NEXTVAL, '혼자 공부하는 자바스크립트', '윤인성', 24000, 10);
INSERT INTO BOOK_LIST VALUES(BOOK_SEQ.NEXTVAL, 'Java의 정석', '남궁성', 30000, 10);
INSERT INTO BOOK_LIST VALUES(BOOK_SEQ.NEXTVAL, '불편한 편의점', '김호연', 14000, 10);
INSERT INTO BOOK_LIST VALUES(BOOK_SEQ.NEXTVAL, '오늘 밤, 세계에서 이 사랑이 사라진다 해도', '이치조 미사키', 14000, 10);
INSERT INTO BOOK_LIST VALUES(BOOK_SEQ.NEXTVAL, '스파이 패밀리(Spy Family)', '엔도 타츠야', 6000, 10);
INSERT INTO BOOK_LIST VALUES(BOOK_SEQ.NEXTVAL, '말장난', '유병재', 17000, 10);

SELECT * FROM BOOK_LIST ORDER BY BOOK_NO ASC;

SELECT * FROM BOOK_ORDER ORDER BY ORDER_NO ASC;

SELECT T1.BOOK_NO, T1.TITLE, T1.WRITER, T1.PRICE, SUM(T1.COUNT) AS TOT_COUNT, T1.PRICE * SUM(T1.COUNT) AS TOT_PRICE
FROM BOOK_ORDER T1
GROUP BY T1.BOOK_NO, T1.TITLE, T1.WRITER, T1.PRICE
ORDER BY BOOK_NO ASC;

SELECT LAST_NUMBER FROM USER_SEQUENCES  WHERE SEQUENCE_NAME = 'ORDER_SEQ';

SELECT  BOOK_NO, STOCK FROM BOOK_LIST;

SELECT  BOOK_NO, STOCK FROM BOOK_LIST WHERE BOOK_NO=3;

update book_list set stock = 5 where book_no = 1;
